### ISSUE TITLE
[HELP] Failed to initialize GTK on macOS

### ISSUE THREAD

**Issue by xaon** [gtk-rs/gtk3-rs#615]
Hi, 

I am trying to use `gtk3-rs` on macOS Catalina, but getting a `Failed to initialize GTK` error:

```
[dependencies]
gtk = "0.14.0"
```

```
use gtk::prelude::*;
use gtk::{ButtonsType, DialogFlags, MessageType, MessageDialog, Window};

fn main() {
    gtk::init().unwrap();
    MessageDialog::new(None::<&Window>,
                       DialogFlags::empty(),
                       MessageType::Info,
                       ButtonsType::Ok,
                       "Hello World").run();
}
```

I have installed gtk3 3.24.23 using macport:

```
port install gtk3
```

The output of `RUST_BACKTRACE=full cargo run`: 

```
     Running `target/debug/gtktest`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BoolError { message: "Failed to initialize GTK", filename: "/Users/L001/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.14.0/src/rt.rs", function: "gtk::rt", line: 123 }', src/main.rs:28:17
stack backtrace:
   0:        0x102472334 - std::backtrace_rs::backtrace::libunwind::trace::h03e89bdd1996f493
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x102472334 - std::backtrace_rs::backtrace::trace_unsynchronized::hb5af08e4de8ca785
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x102472334 - std::sys_common::backtrace::_print_fmt::h4eafc628aec41041
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x102472334 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6a8908fa3ed6f9e8
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x1024887dc - core::fmt::write::h4be00f71c5582919
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/fmt/mod.rs:1110:17
   5:        0x1024704da - std::io::Write::write_fmt::h49e76926070788f1
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/io/mod.rs:1588:15
   6:        0x102473e9f - std::sys_common::backtrace::_print::h2f7b8ad2bea4f859
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x102473e9f - std::sys_common::backtrace::print::h97402070cfceb1a3
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x102473e9f - std::panicking::default_hook::{{closure}}::h1577f0656e419c0e
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:208:50
   9:        0x10247399d - std::panicking::default_hook::h1aef594179c4fd25
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:225:9
  10:        0x1024745a0 - std::panicking::rust_panic_with_hook::h10bc487d002f6c42
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:622:17
  11:        0x102474045 - std::panicking::begin_panic_handler::{{closure}}::hf4cfa78c105ce648
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:519:13
  12:        0x1024727a8 - std::sys_common::backtrace::__rust_end_short_backtrace::h1df96a166e4351c4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x102473faa - rust_begin_unwind
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
  14:        0x10248f3bf - core::panicking::panic_fmt::hea8fe6c9e0720810
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
  15:        0x10248f435 - core::result::unwrap_failed::h58357c1be19e8a7d
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:1355:5
  16:        0x10244f36a - core::result::Result<T,E>::unwrap::h8b9e06c7920ab07d
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:1037:23
  17:        0x10244f97a - gtktest::main::h84df32221ec8edb9
                               at /private/tmp/gtktest/src/main.rs:28:5
  18:        0x10244f2ae - core::ops::function::FnOnce::call_once::h2f642c116c0ced17
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  19:        0x10244f821 - std::sys_common::backtrace::__rust_begin_short_backtrace::hefc42d08da7cf6b9
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:125:18
  20:        0x10244fd24 - std::rt::lang_start::{{closure}}::h19bff61e43fbae31
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:49:18
  21:        0x1024749e1 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h7adc4e20a318e389
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:259:13
  22:        0x1024749e1 - std::panicking::try::do_call::h687af85ae86a6e14
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  23:        0x1024749e1 - std::panicking::try::hf74f2790da0186f3
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  24:        0x1024749e1 - std::panic::catch_unwind::hd14a420ea313edb8
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  25:        0x1024749e1 - std::rt::lang_start_internal::h4428f22d05a79c62
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:34:21
  26:        0x10244fcfe - std::rt::lang_start::h59872a64a81dff2b
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:48:5
  27:        0x10244fa46 - _main
```

```
$ rustc --version
rustc 1.54.0 (a178d0322 2021-07-26)
```

Any idea what's wrong?

Thanks!

**Comment by sdroege** [comment]
Do any other GTK applications work for you? This is GTK itself failing to initialize, nothing related to the bindings. Please report this to https://gitlab.gnome.org/GNOME/gtk/issues/new
