### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jlesage** [gtk-rs/gtk3-rs#684]
```
apk --no-cache add build-base curl git bash
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
source $HOME/.cargo/env
cd /tmp/
git clone https://github.com/gtk-rs/gtk3-rs.git
cd gtk3-rs/examples/
cargo build
```

**Bug description**

Please provide a code sample as small as possible which reproduces the bug.

**Backtrace**

You can get the backtrace running your program with the environment variable `RUST_BACKTRACE=full`.

**Comment by qarmin** [comment]
Looks that this may be really GTK or GTK-rs bug(strange that when I run similar commands a while ago, then it worked fine)

When running czkawka, then it crash in a little different place
```
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x00007f02646ce0e9 in gtk::rt::init () at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.14.3/src/rt.rs:119
        argv = alloc::vec::Vec<alloc::string::String, alloc::alloc::Global> {buf: alloc::raw_vec::RawVec<alloc::string::String, alloc::alloc::Global> {ptr: core::ptr::unique::Unique<alloc::string::String> {pointer: 0x5555563b91a0, _marker: core::marker::PhantomData<alloc::string::String>}, cap: 1, alloc: alloc::alloc::Global}, len: 1}
#2  0x00007f0263e0bb50 in czkawka_gui::main () at czkawka_gui/src/main.rs:87
        exit_program_after_initialization = false
```
which probably points at this line
https://github.com/gtk-rs/gtk3-rs/blob/bd5f76236a2fbcad6e97001f1d9230efad7eee74/gtk/src/rt.rs#L119
